version: 2

# Build settings
build:
  os: ubuntu-20.04  # Set to Linux, as Read the Docs uses a Linux environment
  tools:
    python: "3.12"  # Specify the Python version you need

# Project configuration
python:
  use_sphinx: true  # Indicate that you're using Sphinx for documentation

# Sphinx configuration
sphinx:
  configuration: conf.py  # Path to your Sphinx configuration file

# Build commands
commands:
  - make.bat html  # Use make.bat to build HTML documentation
