version: 2

# Build settings
build:
  os: ubuntu-20.04  # Set to Linux, as Read the Docs uses a Linux environment
  tools:
    python: "3.10"  # Specify the Python version directly as a string

# Sphinx configuration
sphinx:
  configuration: conf.py  # Path to your Sphinx configuration file
  build_dir: _build  # Specify the build directory for Sphinx
